#!/usr/bin/env bash
#*******************************************************************************
# Copyright (c) 2026 Eclipse Foundation and others.
# This program and the accompanying materials are made available
# under the terms of the Eclipse Public License 2.0
# which is available at http://www.eclipse.org/legal/epl-v20.html
# SPDX-License-Identifier: EPL-2.0
#*******************************************************************************
# // Some portions generated by Co-Pilot

# Installation script for vaultctl

set -o errexit
set -o nounset
set -o pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# GitHub repository URL
GITHUB_REPO="https://raw.githubusercontent.com/eclipse-cbi/vaultctl/main"

# Detect best installation directory
detect_install_dir() {
  # If user provided a directory, use it
  if [[ -n "${1:-}" ]]; then
    echo "$1"
    return
  fi
  
  # If running as root, use system directory
  if [[ $EUID -eq 0 ]]; then
    echo "/usr/local/bin"
    return
  fi
  
  # For regular users, check common user bin directories
  if [[ -d "$HOME/.local/bin" ]] && [[ -w "$HOME/.local/bin" ]]; then
    echo "$HOME/.local/bin"
    return
  fi
  
  if [[ -d "$HOME/bin" ]] && [[ -w "$HOME/bin" ]]; then
    echo "$HOME/bin"
    return
  fi
  
  # Default to ~/.local/bin (will be created)
  echo "$HOME/.local/bin"
}

INSTALL_DIR="$(detect_install_dir "${1:-}")"

print_info() {
  printf "${BLUE}%s${NC}\n" "$*"
}

print_success() {
  printf "${GREEN}✓ %s${NC}\n" "$*"
}

print_error() {
  printf "${RED}Error: %s${NC}\n" "$*" >&2
}

print_warning() {
  printf "${YELLOW}⚠ %s${NC}\n" "$*"
}

# Check if running as root or if install dir is writable
check_permissions() {
  # If directory exists and is not writable
  if [[ -d "$INSTALL_DIR" ]] && [[ ! -w "$INSTALL_DIR" ]]; then
    print_error "Installation directory '$INSTALL_DIR' is not writable."
    print_info "Options:"
    echo "  1. Run with sudo: sudo ./install.sh"
    echo "  2. Specify a writable directory: ./install.sh ~/.local/bin"
    echo "  3. Use automatic detection: ./install.sh (will use ~/.local/bin)"
    exit 1
  fi
  
  # If directory doesn't exist, check if parent is writable
  if [[ ! -d "$INSTALL_DIR" ]]; then
    local parent_dir
    parent_dir="$(dirname "$INSTALL_DIR")"
    if [[ ! -w "$parent_dir" ]] && [[ $EUID -ne 0 ]]; then
      print_error "Cannot create directory '$INSTALL_DIR' (parent not writable)."
      print_info "Options:"
      echo "  1. Run with sudo: sudo ./install.sh '$INSTALL_DIR'"
      echo "  2. Specify a writable directory: ./install.sh ~/.local/bin"
      exit 1
    fi
  fi
}

# Download vaultctl.sh from GitHub if not present locally
download_vaultctl() {
  local source_file="$1"
  
  if [[ -f "$source_file" ]]; then
    print_info "Using local vaultctl.sh"
    return 0
  fi
  
  print_info "vaultctl.sh not found locally, downloading from GitHub..."
  
  # Check if curl is available
  if ! command -v curl &> /dev/null; then
    print_error "curl is required to download vaultctl.sh from GitHub"
    print_info "Please install curl or clone the repository manually"
    exit 1
  fi
  
  # Download vaultctl.sh
  if curl -fsSL "${GITHUB_REPO}/vaultctl.sh" -o "$source_file"; then
    print_success "Downloaded vaultctl.sh from GitHub"
    chmod +x "$source_file"
    return 0
  else
    print_error "Failed to download vaultctl.sh from GitHub"
    print_info "Please check your internet connection or clone the repository manually:"
    echo "  git clone https://github.com/eclipse-cbi/vaultctl.git"
    exit 1
  fi
}

# Create symlink
install_cli() {
  local source_file="${SCRIPT_DIR}/vaultctl.sh"
  local target_file="${INSTALL_DIR}/vaultctl"
  
  # Download if not present locally
  download_vaultctl "$source_file"
  
  if [[ ! -f "$source_file" ]]; then
    print_error "Source file not found: $source_file"
    exit 1
  fi
  
  # Make source file executable
  chmod +x "$source_file"
  
  # Create install directory if it doesn't exist
  if [[ ! -d "$INSTALL_DIR" ]]; then
    print_info "Creating directory: $INSTALL_DIR"
    mkdir -p "$INSTALL_DIR"
  fi
  
  # Remove existing symlink or file
  if [[ -L "$target_file" ]] || [[ -f "$target_file" ]]; then
    print_info "Removing existing installation..."
    rm -f "$target_file"
  fi
  
  # Create symlink
  print_info "Creating symlink: $target_file -> $source_file"
  ln -s "$source_file" "$target_file"
  
  print_success "vaultctl installed successfully to $target_file"
}

# Check PATH
check_path() {
  if [[ ":$PATH:" != *":$INSTALL_DIR:"* ]]; then
    print_warning "$INSTALL_DIR is not in your PATH"
    print_info "Add it to your PATH by adding this line to your ~/.bashrc or ~/.zshrc:"
    echo ""
    echo "  export PATH=\"\$PATH:$INSTALL_DIR\""
    echo ""
  fi
}

# Show usage
show_usage() {
  cat << EOF
Usage: ./install.sh [install_directory]

Install vaultctl CLI tool to your system.

Arguments:
  install_directory    Directory where to install vaultctl
                       If not specified, auto-detects best location:
                       - ~/.local/bin (for regular users)
                       - /usr/local/bin (for root)

Examples:
  ./install.sh                         # Auto-detect best location (recommended)
  ./install.sh ~/.local/bin            # Install to user directory
  sudo ./install.sh /usr/local/bin     # Install to system directory
  ./install.sh /opt/vaultctl/bin       # Install to custom directory

EOF
}

# Main
main() {
  if [[ "${1:-}" == "-h" ]] || [[ "${1:-}" == "--help" ]]; then
    show_usage
    exit 0
  fi
  
  print_info "Installing vaultctl CLI..."
  print_info "Installation directory: $INSTALL_DIR"
  echo ""
  
  check_permissions
  install_cli
  check_path
  
  echo ""
  print_success "Installation complete!"
  print_info "Try running: vaultctl help"
}

main "$@"
